### ISSUE TITLE
[📑 Docs]: Is there any documentation on how to use it?

### ISSUE THREAD

**Issue by Yuutakasan** [asyncapi/openapi-schema-parser#236]
### What Dev Docs changes are you proposing?

I am currently working on a mechanism for OpenAPI and AsyncAPI to work together.Originally, I was using OpenAPI Generator, but I am planning to migrate to AsyncAPI Generator to create a mechanism that can be used in conjunction with OpenAPI and AsyncAPI.
I am looking for a mechanism that can parse OpenAPI Spec, and I thought this mechanism could be useful, but I don't know how to use it.
Could you please document it for me or give me some simple instructions on how to use it?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by derberg** [comment]
Hey @Yuutakasan 

this project  focus on supporting reusability of OpenAPI Schema (just for message payloads) inside AsyncAPI.

I guess you're looking for OpenAPI -> AsyncAPI converter, is that right?

**Comment by Yuutakasan** [comment]
@derberg 
I was trying it last week and finally understood.Thanks for your reply.

Currently, I am developing a mechanism to run a backend request with event sourcing and asynchronous processing after requesting an OpenAPI Spec.Currently, I only have a program that is processed by OpenAPi generator and I am writing it in OpenAPi generator, but now I am trying to generate the program automatically in AsyncAPi generator based on AsyncAPi Spec.

OpenAPi Spec and AsyncAPi Spec have to work together, but for interface definition and the reason of not wanting to maintain the program twice, I want to be able to output OpenAPi Spec and AsyncAPi Spec from a single generator.I will do so.

So, I am considering whether there is a way for AsyncAPI generator to do OpenAPI Spec and AsyncAPI Spec.

The current direction of consideration is as follows
(1) AsyncAPI generator can parse OpenAPI Spec and generate the program automatically.
Convert OpenAPI Spec to AsyncAPI Spec and generate it automatically with AsyncAPI Generator.

Currently, we are trying to modify OpenAPI Schama parser to OpenAPI Spec parser to achieve 1 above.

If you can think of any other way to do this, it would be greatly appreciated.

**Comment by derberg** [comment]
Hey, thanks for sharing all the details

In AsyncAPI Generator there is no discussion about supporting OpenAPI atm - that would cause some more complexity to codebase and also not many people request it.

I suggest option 2. And actually we have a bounty issue for it (advanced which means we can pay $400 for the work) -> https://github.com/asyncapi/converter-js/issues/233
You can join our Slack and chat in DM with Jonas who submitted the issue.
